export const cities = [
   { id: 1, name: 'Buenos Aires', countryId: 1 },
   { id: 2, name: 'Córdoba', countryId: 1 },
   { id: 3, name: 'Rosario', countryId: 1 },
   { id: 4, name: 'Mar del Plata', countryId: 1 },
   { id: 5, name: 'Río de Janeiro', countryId: 2 },
   { id: 6, name: 'Sao Paulo', countryId: 2 },
   { id: 7, name: 'Brasilia', countryId: 2 },
   { id: 8, name: 'Natal', countryId: 2 },
   { id: 9, name: 'Bogota', countryId: 3 },
   { id: 10, name: 'Medellin', countryId: 3 },
   { id: 11, name: 'Cali', countryId: 3 },
   { id: 12, name: 'Cartagena', countryId: 3 },
   { id: 13, name: 'San Jose', countryId: 4 },
   { id: 14, name: 'cartago', countryId: 4 },
   { id: 15, name: 'Limon', countryId: 4 },
   { id: 16, name: 'Heredia', countryId: 4 },
   { id: 17, name: 'Quito', countryId: 5 },
   { id: 18, name: 'Guayaquil', countryId: 5 },
   { id: 19, name: 'Cuenca', countryId: 5 },
   { id: 20, name: 'Santo Domingo', countryId: 5 },
   { id: 21, name: 'Madrid', countryId: 6 },
   { id: 22, name: 'Barcelona', countryId: 6 },
   { id: 23, name: 'Valencia', countryId: 6 },
   { id: 24, name: 'Sevilla', countryId: 6 },
   { id: 25, name: 'Nueva York', countryId: 7 },
   { id: 26, name: 'Los Ángeles', countryId: 7 },
   { id: 27, name: 'Chicago', countryId: 7 },
   { id: 28, name: 'Houston', countryId: 7 },
   { id: 29, name: 'Nueva York', countryId: 8 },
   { id: 30, name: 'Los Ángeles', countryId: 8 },
   { id: 31, name: 'Chicago', countryId: 8 },
   { id: 32, name: 'Houston', countryId: 8 }
 ];
 